### ISSUE TITLE
Create level design V1

### ISSUE THREAD

**Issue by jonathandavidlewis** [Screwloose-Games/brackeys-game-jam-sept-2024#35]
The game should be able to be completed in 5 minutes by a novice player.
Calibrate the water rising speed to make it slightly easier, but not "too fast"
Allow them to fall as far as possible. (they will get caught with water)

## Early on, what makes it less punishing:
- [ ] Platforms are against the side walls and prevent overshooting.
- [ ] When you fall, you do not fall far. (platforms are wide and there are few spaces)
- [ ] The distance between platforms is about 50-75% of jump height.
- [ ]  The gaps from level to level are alternating so that the position of a gap in one level is very different from the position of the gap in the next level.
- [ ] There are no dead ends, paths that take you up a platform on one side, but don't lead to the next level up.
- [ ] When you land on a platform, it is very likely you are positioned such that you are already lined up for the next platform.

## More Challenging

- [ ] Increase the challenge through the above and other changes as time goes on
- [ ] The distance between one platform and the next is near the end of max jump height.
- [ ] Smaller platforms
- [ ] Overall, more gaps
- [ ] Gaps extend downward further (falling several levels)
- [ ] Platforms are not against the side walls, so if you overshoot, you can fall off the side.

**Comment by Simpathey** [comment]
Sweet, gonna try and get this done so we can see what the game will feel like!
